[font]
size = 8.0

[colors]
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.normal]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'
  
[colors.bright]
black = '#565f89'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

[colors.cursor]
text = '#1A1B26'
cursor = '#A9B1D6'

[colors.selection]
text = '#C0CAF5'
background = '#2E3C7E'
